# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import structlog

from os2mo_init.autogenerated_graphql_client import GraphQLClient

logger = structlog.stdlib.get_logger()


async def ensure_facets(
    client: GraphQLClient,
    config_facets: set[str],
) -> None:
    """
    Ensure that the given facets exists.

    Args:
        client: MO GraphQL client.
        config_facets: Desired facets.
    """
    logger.info("Ensuring facets", facets=config_facets)

    existing_facets = {
        o.current.user_key
        for o in (await client.facets_query()).objects
        if o.current is not None
    }
    logger.debug("Existing facets", existing=existing_facets)

    missing_facets = config_facets - existing_facets

    for user_key in missing_facets:
        logger.info("Creating facet", user_key=user_key)
        await client.create_facet_mutation(
            user_key=user_key,
        )
