# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import structlog

from os2mo_init.autogenerated_graphql_client import GraphQLClient
from os2mo_init.config import ConfigRootOrganisation

logger = structlog.stdlib.get_logger()


async def ensure_root_organisation(
    client: GraphQLClient,
    config_root_organisation: ConfigRootOrganisation,
) -> None:
    """
    Ensure that the root organisation exists with the given configuration.

    Args:
        client: MO GraphQL client.
        config_root_organisation: Desired root organisation.
    """
    logger.info("Ensuring root org", root_org=config_root_organisation)

    existing_root_org = await client.root_org_query()
    logger.debug("Existing root org", existing=existing_root_org)

    if (
        existing_root_org.municipality_code
        != config_root_organisation.municipality_code
    ):
        logger.info("Updating org org")
        await client.root_org_create(
            municipality_code=config_root_organisation.municipality_code,
        )
