# Generated by ariadne-codegen on 2024-08-12 15:35
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class ITSystemsQuery(BaseModel):
    itsystems: "ITSystemsQueryItsystems"


class ITSystemsQueryItsystems(BaseModel):
    objects: List["ITSystemsQueryItsystemsObjects"]


class ITSystemsQueryItsystemsObjects(BaseModel):
    current: Optional["ITSystemsQueryItsystemsObjectsCurrent"]


class ITSystemsQueryItsystemsObjectsCurrent(BaseModel):
    uuid: UUID
    user_key: str
    name: str


ITSystemsQuery.update_forward_refs()
ITSystemsQueryItsystems.update_forward_refs()
ITSystemsQueryItsystemsObjects.update_forward_refs()
ITSystemsQueryItsystemsObjectsCurrent.update_forward_refs()
