# Generated by ariadne-codegen on 2024-08-13 19:15
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class RootOrgCreate(BaseModel):
    org_create: "RootOrgCreateOrgCreate"


class RootOrgCreateOrgCreate(BaseModel):
    uuid: UUID


RootOrgCreate.update_forward_refs()
RootOrgCreateOrgCreate.update_forward_refs()
