# Generated by ariadne-codegen on 2024-08-13 19:15
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateClassMutation(BaseModel):
    class_update: "UpdateClassMutationClassUpdate"


class UpdateClassMutationClassUpdate(BaseModel):
    uuid: UUID


UpdateClassMutation.update_forward_refs()
UpdateClassMutationClassUpdate.update_forward_refs()
