# Generated by ariadne-codegen on 2024-08-12 15:35
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateITSystemMutation(BaseModel):
    itsystem_update: "UpdateITSystemMutationItsystemUpdate"


class UpdateITSystemMutationItsystemUpdate(BaseModel):
    uuid: UUID


UpdateITSystemMutation.update_forward_refs()
UpdateITSystemMutationItsystemUpdate.update_forward_refs()
